// Generated by CoffeeScript 1.9.1
(function() {
  var Bacon, Types;

  jest.dontMock('../typed-bacon.coffee');

  Bacon = require('baconjs');

  Types = require('../typed-bacon.coffee').Types;

  describe('Types', function() {
    return describe('existy', function() {
      return it('finds if an object is existy', function() {
        expect(Types.Existy.isType(null)).toBe(false);
        expect(Types.Existy.isType(void 0)).toBe(false);
        expect(Types.Existy.isType(0)).toBe(true);
        return expect(Types.Existy.isType("")).toBe(true);
      });
    });
  });

}).call(this);
